- type: replace
  path: /releases?/name=jumpbox?
  value:
    name: jumpbox
    version: 4.8.3
    url: https://bosh.io/d/github.com/cloudfoundry-community/jumpbox-boshrelease?v=4.8.3
    sha1: 7d256256952543073689a1e61daf3a266cb0b651
